version: '3.8'

services:
  password-manager:
    build: .
    container_name: secure-password-manager
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: password-manager-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - password-manager
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: password-manager-network
